---
title: "Job Fair Optimization"
output: html_notebook
---

```{r}
library(tidyverse)
library(readr)
```

```{r}
companies = read_csv2("companies.csv")
colnames(companies)=c('company','sector','exclusive')
companies$exclusive = if_else(is.na(companies$exclusive),F,companies$exclusive=='ja')
```

```{r}
sectors = companies %>% 
  group_by(sector) %>%
  summarise(n=n())%>%
  arrange(desc(n))

topsectors = sectors$sector
```

```{r}
lots = read_csv2("lots.csv",col_names = FALSE,)
lots[lots==T]=''
```


```{r}
source("optimizers.R")
#randomlotcompany(companies,lots)
solutions = data.frame(stringsAsFactors = F)
bestsolution = NULL
bestsolution_n_unassigned_companies = 100000
for (try in 1:3) {
  for (method in c('randomlotcompany','biggestsectorsfirst')) {
    solution = case_when(
      method == 'randomlotcompany' ~ randomlotcompany(companies, lots),
      method == 'biggestsectorsfirst' ~ biggestsectorsfirst(companies, lots),
      TRUE ~ list(F,"kaka",-1)
    )
    if(solution[[3]]<bestsolution_n_unassigned_companies){
      bestsolution=solution[[2]]
      bestsolution_n_unassigned_companies=solution[[3]]
    }
    solutions = rbind(solutions,
                      list(method,try, solution[[1]], solution[[3]]))
  }
}
colnames(solutions) = c('method','try','complete','n_unassigned_companies')
solutions
```

```{r}
lots_list = data.frame(stringsAsFactors = F)
for (c in 1:ncol(bestsolution))
  for (r in 1:nrow(bestsolution)) {
    cat(bestsolution[r, c])
    #cat(companies[companies$company == bestsolution[r, c], ]$sector)
    if (!is.na(bestsolution[r, c]) & bestsolution[r, c] != '')
      lots_list = rbind(lots_list, list(r, c, bestsolution[r, c], companies[companies$company ==
                                                                              bestsolution[r, c],]$sector),stringsAsFactors=F)
  }
colnames(lots_list) = c('row', 'column', 'company', 'sector')
```

```{r}
lots_list %>%
  ggplot(aes(x=column,y=row,fill=sector,label=company)) + geom_tile()+geom_text(angle=45)
```


